### ISSUE TITLE
Use on Moodle 3.5.2

### ISSUE THREAD

**Issue by rexrob3** [iandavidwild/moodle-mod_wavefront#14]
I have tried to run the plug in on Moodle 3.5.2 but when I go to look at the model all I see is a rectangle with the name of the model inside it.

**Comment by Fae6068123** [comment]
It would be nice if users are able to upload the model. Currently users can't upload the model and users getting message 'No model files were found in this gallery'

**Comment by iandavidwild** [comment]
> It would be nice if users are able to upload the model. Currently users can't upload the model and users getting message 'No model files were found in this gallery'

You can use roles and permissions to specify which users can upload models. By default it's anyone with the default teacher role or above.
