### ISSUE TITLE
Better handling of WebGL errors

### ISSUE THREAD

**Issue by mudrd8mz** [iandavidwild/moodle-mod_wavefront#3]
By default I have the discrete GPU off on my notebook to safe the battery. As a result, the model is not displayed to me and all I can see is the description box. Only by going to the JS console in the browser, I can see:

![image](https://cloud.githubusercontent.com/assets/85831/25149240/0531e63e-247e-11e7-95d2-057f125b31aa.png)

It would help if the JS caught such errors and displayed some human-friendly message to the student.

**Comment by iandavidwild** [comment]
Have ensured that the JS fails gracefully and a suitable warning message is displayed if WebGL is not enabled.

**Comment by mudrd8mz** [comment]
I can confirm I get much nicer warning now, thanks.
