### ISSUE TITLE
Capability addcomment granted to guests by default

### ISSUE THREAD

**Issue by mudrd8mz** [iandavidwild/moodle-mod_wavefront#4]
The db/access.php defines the capability 'mod/wavefront:addcomment' and declares that this capability should be marked as allowed for guests by default. That is nonsense as guests by design can't create any content in moodle, including comments.

**Comment by iandavidwild** [comment]
Have corrected that capability. This was copied over from the Lightbox Gallery capabilities so I'm not sure if they would need to be corrected too?
