### ISSUE TITLE
XSS via edit_model.php

### ISSUE THREAD

**Issue by mudrd8mz** [iandavidwild/moodle-mod_wavefront#5]
There are actually two problems I've noticed here:

* The edit_model.php does not check the capability, so any student can actually visit that page directly and edit/create new models (I was just able to reproduce this)
* Additionally, the `mod_wavefront_renderer::display_model()` does not use `format_text()` on the description, so it is sent in the raw state to the browser.

Together, this allows any logged-in user to submit malicious JS code into the description field which is then executed in other users' browsers.

**Comment by iandavidwild** [comment]
1) format_text() is now being used on the model description.
2) edit_model.php is now checking for the wavefront:edit capability.
